image_width: 640
image_height: 480
camera_name: my_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [425.21719,   0.     , 371.23129,
           0.     , 425.44815, 215.38726,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.055592, -0.049383, -0.000971, 0.001553, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [430.54202,   0.     , 372.17185,   0.     ,
           0.     , 431.77252, 214.39974,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
