image_width: 640
image_height: 480
camera_name: my_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [426.29465,   0.     , 369.91393,
           0.     , 425.41937, 212.43308,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.058897, -0.055214, -0.000418, -0.000933, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [432.06711,   0.     , 369.04883,   0.     ,
           0.     , 431.38647, 211.76291,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
